### ISSUE TITLE
NPM Install - Windows Issue

### ISSUE THREAD

**Issue by umutcakan** [humaine-anac/agent-jok#3]
Hey there,

I have followed README and completed 7 steps with no problem. But when I tried to launch the agent I got an error. Step and error information can be found below:

**STEP 8:** Finally, to instantiate the agent, run:
**COMMAND:** node agent-jok.js -level 2 -port 14007 > agent001.log &

**ERROR:**

internal/modules/cjs/loader.js:985
  throw err;
  ^

Error: Cannot find module './appSettings.json'
Require stack:
- D:\HUMAINE\agent-jok\agent-jok.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
    at Function.Module._load (internal/modules/cjs/loader.js:864:27)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (D:\HUMAINE\agent-jok\agent-jok.js:4:21)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ 'D:\\HUMAINE\\agent-jok\\agent-jok.js' ]
}

Since I am not familiar with the node, unfortunately, I could not resolve this problem. I will be glad if you can help me with this one. 

Footnote: I have launched the humaine.exe before running this command and I have tried without running it, I am afraid there was no difference.

**Comment by umutcakan** [comment]
I have noticed that in order to find that file, I have needed to change appSettings.json.template to appSettings.json. That was one simple issue that I have noticed a bit late.
